//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tahsilatbilgileri
    {
        public short ID { get; set; }
        public string Firma_Adi { get; set; }
        public string Tahsil_Yapan { get; set; }
        public string Odeme_Yapan { get; set; }
        public string Banka { get; set; }
        public string Sube { get; set; }
        public string Tahsilat_Turu { get; set; }
        public Nullable<decimal> Tahsilat_Miktari { get; set; }
        public string Hesap_Iban { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> Ssk { get; set; }
        public Nullable<decimal> Bagkur { get; set; }
        public Nullable<decimal> Kdv { get; set; }
        public Nullable<decimal> Kdv_2 { get; set; }
        public Nullable<decimal> Muhtasar { get; set; }
        public Nullable<decimal> Gelir_Vergisi { get; set; }
        public Nullable<decimal> Gecici_Vergi { get; set; }
        public Nullable<decimal> Kurumlar_Vergisi { get; set; }
        public Nullable<decimal> Yapılandırma_Poset { get; set; }
        public Nullable<decimal> Cesitli_Tahsilat { get; set; }
        public Nullable<decimal> Diger { get; set; }
        public Nullable<decimal> Diger_Eski_Yillar { get; set; }
        public string Not { get; set; }
    }
}
